Add-works&about-sections
MILINDI7/Portfolio-setup-mobile-first pull request #2
Opened 2023-01-13 14:01 UTC by MILINDI7

## What?
creating the what we do in work section and what about us in the about sections of the portfolio.

## Why?
As required in the project requirements, we are required to add the work and about sections onto the portfolio.

## How?
By the use of flex and grid to display different elements of the work and about section, after creating a good workflow, awe added and pushed the following changes.

2023-01-13 14:36 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @MILINDI7 , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 14:36 UTC, bobb-Rob commented on index.html
> +      <div class="cards">
- [ ] The main container of the projects cards has a `display:grid` declared on it. Please use grid property to layout this projects.

2023-01-13 14:36 UTC, bobb-Rob commented on index.html
> +          <button class="submition">See Project</button>
- [ ] This button has a white text. Also, please implement the various states of the button e.g hover, active etc.

Your button
![image](https://user-images.githubusercontent.com/84156714/212343409-5fa86a46-a9d8-4492-aadc-1db1889851ba.png)

Figma project button 
![image](https://user-images.githubusercontent.com/84156714/212343544-e195b58a-e4b4-4bca-830a-d8751fb47623.png)

Various button state
![image](https://user-images.githubusercontent.com/84156714/212343659-60076360-500e-4490-99df-2c797217422b.png)

2023-01-13 14:36 UTC, bobb-Rob commented on index.html
> +        </div>
- [ ] The technology categories ("Languages", "Frameworks" and "Skills") are in a `ul`, each of them in a `li`.  The technology in each category(e.g., "JavasScript", "HTML" and "CSS") are also a list `ul` and each of them a `li`. Essentially you will have a `ul` tag inside each `li` tag. Please fix this.

2023-01-14 11:09 UTC, MILINDI7 commented on index.html
> +          <button class="submition">See Project</button>
These are to be implemented in the next block.

2023-01-14 11:14 UTC, MILINDI7 commented on index.html
> +        </div>
That's what I did.

2023-01-14 13:29 UTC, RaoAkif approved these changes
## STATUS: APPROVED 🎉🎉🎉

Hi @MILINDI7, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approve-image](https://ci5.googleusercontent.com/proxy/zq80mRZVpq-eAhdzmvNYP-LJmESV4U2mCLkUDj-J77H6FKB6oLO-eL8kGFENlnk15aQQPnJ2K7hSGZiaZBHMKFZEM6yCAT5H0leJxszpiJ_ZRxNc5L9uv6Wf0BFZUomZYiYN6ppiHgltD6qjc_Kh8RbH3b4nVLPghJlpfxM29IAi_q8djloxFmcQQ_I2iIY_rYXVUeBiSfNsVRfk0iq3wo75_nf9QHejNs5EwcDwp7n4vukAV0rFF6xBnAenIBlJ9_CuSGN37pZ0FDROc_LU_rInohwgD5sTJnITUxeXsq5juhu5btEu0AhtqpFV5MDVTQMfZw=s0-d-e1-ft#https://camo.githubusercontent.com/b4e8f035e0f2d20302034402026b8df675e3a9dd93b722d1b0a047112e68044d/68747470733a2f2f632e74656e6f722e636f6d2f4a52665739444c534f764141414141432f7365616c2d7365616c2d6f662d617070726f76616c2e676966)

## Highlights
✔ Linters are on point 
✔ Splendid work with the README file
✔ Great use of GitHub flow
✔ Good code design and implementation

## Optional suggestions
- Change the `button` tags in `My Recent Works` & `About Me` sections to `p` tag, and give it padding.
- _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 13:29 UTC, RaoAkif commented on index.html
> +        </div>
[OPTIONAL] Yup, you did that correctly. But since it is not a button, the button tag won't be used here. you can use a `p` tag instead, and add `padding: 8px 12px;` as per FIGMA design.

2023-01-14 13:29 UTC, RaoAkif commented on index.html
> +           <li><button class="html">html</button></li>
[OPTIONAL] These are not buttons, the button tag won't be used here. you can use a p tag instead and add `padding: 8px 12px;` as per FIGMA design.

2023-01-14 18:11 UTC, merged